name: CI

on:
  pull_request:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-ci-${{ hashFiles('**/Cargo.toml') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt, clippy
          override: true
      - name: CI job
        # See tools/ci/src/main.rs for the commands this runs
        run: cargo run -p ci
      - name: Ensure docs compile
        run: cargo doc --no-deps
        env:
          RUSTDOCFLAGS: -Dwarnings
